import type { Metadata } from 'next';
// eslint-disable-next-line camelcase
import { Fira_Sans } from 'next/font/google';
import { ReactNode } from 'react';

import './globals.css';
import Header from './components/Header';
import Footer from './components/Footer';

const firaSans = Fira_Sans({
	subsets: ['latin'],
	weight:  ['400', '500', '600', '700'],
	display: 'swap',
});

export const metadata: Metadata = {
	title:       'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
  children: ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${firaSans.className} antialiased  bg-surface-4`}>
				<Header />
				{children}
				<Footer/>
			</body>
		</html>
	);
}
